### ISSUE TITLE
How to get model parameters of linearmodels?

### ISSUE THREAD

**Issue by ybdesire** [bashtage/linearmodels#129]
https://stackoverflow.com/questions/47645349/how-to-get-model-parameters-of-linearmodels

**Comment by bashtage** [comment]
The answer to your other question explains the main issue.  You can, however, get the `beta` parameters and `e` since these are in `params` and `resids` from a model result. There isn't currently enough in the model to get fitted values when there are fixed effects since you would need to fixed-effect purged `exog` variable data to compute these values. These are not exposed.

**Comment by ybdesire** [comment]
Got that. Thanks @bashtage for the update.
