### ISSUE TITLE
R-squared in PanelOLS

### ISSUE THREAD

**Issue by iheus** [bashtage/linearmodels#157]
Using PanelOLS, I get different R-squared's than those produced in statistical software like STATA or ols in the statsmodels package. The reason might be that PanelOLS seems to return R-squared by removing fixed effects even if the model includes FEs (correct me if I'm wrong). In economics papers, this is perhaps less common. Is there any way to produce the R-squared without removing FEs?

**Comment by bashtage** [comment]
You can directly compute the R2 that Stata uses with

```python
import pandas as pd

df = pd.concat([y, res.fitted_values],1).dropna()
print(df.corr().iloc[0,1])
```

I'm surprised you recommend against linearmodels in your teaching material and instead suggest using dummies with statsmodels.  The statsmodels approach isn't always correct depending on the covariance structure and whether dummies are effects or consistently estimable parameters. The dummy approach also doesn't work when the panel is large and has many entities (it is either very slow or infeasible due to the large, sparse matrix).

**Comment by iheus** [comment]
Thanks! I'm surprised that you have explored my teaching material. :) I haven't encountered the type of error you mention yet for statsmodels, but statsmodels seemingly falsely report a null result when the variable is correlated with fixed effects and therefore is dropped. Also, the computation speed tends to be longer for statsmodels than linearmodels. Despite these drawbacks, I still chose statsmodels (although I taught about linearmodels in my class too!) as I thought about (a) a risk that my students would think that the reported R-squared is the correct one, (b) exporting the regression results as a tex file seems to be easy for statsmodels, and (c) it's related to (b) but I couldn't easily find basic examples for functions/methods included in linearmodels. Regarding (b) and (c), what would be the best way to export regression outcomes in the tex format with the correct R-squared like statsmodels do?

**Comment by bashtage** [comment]
It is difficult to define the "right" R2 in a panel regression.  IMO the correct treatment of fixed effects is to consider then as errors, so that y_it=x_it beta + u_i + e_it ( +v_t) where u_i is the entity effect and v_t would be time effect. In most panels where N is big but T is small, fixed effects cannot be consistently estimated.  Ideally one would teach students how to interpret the R2 in a panel (which is nontrivial) and what different measure capture (and what they don't)

Exporting is nearly identical to statsmodels since the results use the statsmodels summary. 

``
res.summary.to_latex()
```

Pretty much everything is documented here:

https://bashtage.github.io/linearmodels/panel/reference.html

I have improved the docstring for summary to be explicit about export based on your feedback. Thanks.

**Comment by iheus** [comment]
Thank you @bashtage ! It's good to know how one can easily export results in tex format. I also very much look forward to any further update on R2 measures!

**Comment by ClaireCuiFighting** [comment]
Could you also explain the difference between R-squared and R-squared (Overall)? Are they adjusted R-squares? @bashtage

**Comment by bashtage** [comment]
I added documentation that you will find

https://bashtage.github.io/linearmodels/devel/panel/mathematical-formula.html#r-2-estimates
