### ISSUE TITLE
Dummy variable regression in PooledOLS generates an error

### ISSUE THREAD

**Issue by spring-haru** [bashtage/linearmodels#188]
I conducted a dummy variable regression based on  [this page](
https://bashtage.github.io/linearmodels/doc/panel/examples/examples.htm), using `linearmodels (PooledOLS)` and `statsmodels` with the same formula (see below). The latter finishes computation and generates a result, whereas `linearmodels` produces an error message:

`ValueError: exog does not have full column rank.`

I wonder what is happening in `linearmodels`. Does a bug cause this? Can you shed light on this?

```
import pandas as pd
from linearmodels.datasets import wage_panel
from linearmodels.panel import PooledOLS
from statsmodels.formula.api import ols

data = wage_panel.load()
year = pd.Categorical(data.year)
nr = pd.Categorical(data.nr)
data = data.set_index(['nr', 'year'])
data['year'] = year
data['nr'] = nr

# formula
formula = 'lwage ~ married + union + educ + year + year:educ + nr'

# statsmodels -----------
result_sm = ols(formula, data=data).fit()
# show selected parameters
condition = result_sm.params.index.str.contains('nr').tolist()
result_sm.params[[not i for i in condition]]

# linearmodels ----------
result_lm = PooledOLS.from_formula(formula, data=data).fit()

# generate the error message 'ValueError: exog does not have full column rank.'
```

**Comment by bashtage** [comment]
You have a singular "design matrix" when you include `'year:educ + nr`, and since year:educ is continuous, nothing is dropped by patsy.

In this case, statsmodels is effectively giving you random results (they depend on the linear algebra library used, the platform and the order of variables) since the exogenous variables are rank deficient.  You can verify the reduced rank of `exog` in statsmodels by

```python
import pandas as pd
from linearmodels.datasets import wage_panel
from linearmodels.panel import PooledOLS
from statsmodels.formula.api import ols

data = wage_panel.load()
year = pd.Categorical(data.year)
nr = pd.Categorical(data.nr)
data = data.set_index(['nr', 'year'])
data['year'] = year
data['nr'] = nr

# formula
formula = 'lwage ~ married + union + educ + year + year:educ + nr'

# statsmodels -----------
mod = ols(formula, data=data)
result_sm = mod.fit()
exog = mod.exog
import numpy as np
print(exog.shape[1])
print(np.linalg.matrix_rank(exog))
print('More parameters than the rank of exog, see...')
print(result_sm.params.shape[0])
assert np.linalg.matrix_rank(exog) ==  exog.shape[1]
```

**Comment by bashtage** [comment]
@josef-pkt Looks like a bug in the formula interface where rank isn't correctly checked.

**Comment by bashtage** [comment]
The philosophy of `lm` is to be strict and explicit.  This is an important contrast to R and Stata which will make choices for users when matrices are rank deficient.  `statsmodels` has the same philosophy as `lm` from what I have seen, so this is likely a bug.

**Comment by josef-pkt** [comment]
The linear regression models, OLS, WLS, and in some cases estimation based on iterative reweighted least squares give a pinv regularized solution. statsmodels does not raise an exception for singular exog by design, but there should be the warning message in `summary`.

The parameters are not identified, but the pinv solution is not "arbitrary" and does not depend on the linalg library (except in edge cases). The solution is essentially PCA-regression with a very small threshold, which is theoretically also the limit case for Ridge regression with diminishing penalization weight.
(R drops variables using pivoting QR, and, AFAIK, Stata drops sequentially (non-pivoting QR?))

I need to switch computer to run and look at the example.

**Comment by bashtage** [comment]
It would probably be helpful if a warnign was printed when the model was fit, since it is plausible that people don't examine the summary in many circumatances. 

`pinv` is _arbitrary_ in the same way that PCA uses an arbitrary (but convenient) normalization.  There are infinitely many normalizations that would produce the same sum of squares, and pinv is simply choosing one.  Parameter estimates from rank deficient regression are as interpretable as the factors from a PCA (i.e., they are not, but fitted values may be interesting).
