### ISSUE TITLE
Multicollinearity in Panel Data in Python

### ISSUE THREAD

**Issue by lucashusted** [bashtage/linearmodels#193]
Hi, I'm new to github, so pardon me if this is not the venue to suggest things for future releases, but I think it would be incredibly useful for future users of this package to have a way to run models in PanelOLS or in whatever estimation strategy they want, where the solver automatically drops dummies (and notifies you) when there is perfect multicollinearity in the regressors. This is how Stata operates, and I imagine R has similar functionality. For an example using the data that you provide as test data, I attempt to run a PanelOLS on a fairly simple model, but instead of using `expersq` I use `exper`. This clearly results in some singularity in the resulting matrix.

```
# Load the test data
import statsmodels.api as sm
from linearmodels.datasets import wage_panel
import pandas as pd
data = wage_panel.load()
year = pd.Categorical(data.year)
data = data.set_index(['nr', 'year'])
data['year'] = year
print(wage_panel.DESCR)
print(data.head())

# Run the regression
from linearmodels.panel import PanelOLS
exog_vars = ['exper','union','married']
exog = sm.add_constant(data[exog_vars])
mod = PanelOLS(data.lwage, exog, entity_effects=True, time_effects=True)
fe_te_res = mod.fit()
print(fe_te_res)
```

Also, you can see a version where I recreate how Stata would estimate the exact same model here: https://stackoverflow.com/questions/55071706/multicollinearity-in-panel-data-in-python

**Comment by bashtage** [comment]
The philosophy of linearmodels, and mostly of statsmodels (and python as a whole) is that explicit is better than implicit.  This means estimating the model asked for or erroring when this is impossible (with a hopefully helpful error).  Automatic variable dropping feels like "magic" since there are always multiple choices.  In the example you provided, the choice is obvious.  It is possible to construct examples where there isn't a single explanatory variable that can be uniquely excluded (e.g., a fixed effect is nested by a linear combination of 2 or more explanatory variables). 

My initial reaction is that I'm unlikely to implement this feature.

**Comment by lucashusted** [comment]
I think that the issue is that in panel data, researchers always want to have the option to fully saturate a model, and multicollinearity when including a variety of dummies is incredibly common. As I was able to show in your test data, a researcher wouldn't know a-priori that they couldn't regress log wages on experience and time + unit fixed effects. I'm not sure if this is a contrived dataset, but there is a reason that all of your examples only use `experience^2` and not `experience`.

I think two solutions are possible:
1. A stand-alone method for helping the researcher determine what are valid dummies and which aren't.
2. At the very least, an output to accompany the error that tells the researcher what went "wrong". It's fine having to have the researcher work a bit to make their regression better, but many use the regression output to learn about the underlying data, and a vague error saying the "The model cannot be estimated." Isn't useful for debugging.

**Comment by bashtage** [comment]
When including dummies that absorb, the problem isn't the dummies, it is the included variables.  A variable that is one dummy away from being absorbed is just a recoded effect.

I can see the point of having a more detailed and helpful error, in particular listing the columns that are problematic.  My philosophical objection to running the model is that the coefficient no longer means what one might think they mean.  The example with time effects and no `exper` is a canonical textbook example (literally from Wooldridge) of not including some variables that are absorbed.  If I drop one of the time effects and report a coefficient on `exper`,this coefficient is no longer meaningful since it is actually a time effect even though it is labeled `exper` in the table.

I don't think a stand-alone method is needed, since one can run explanatory variables as the dependent variable in PanelOLS with all included effects to pre-test for absorption, if this is of interest.

**Comment by bashtage** [comment]
The error message attempts to list problematic variables, or combinations of variables that are problematic when removing effects produces a variable that is perfectly collinear with another included variable.
