### ISSUE TITLE
Fama Macbeth add attribute for all coefficents

### ISSUE THREAD

**Issue by dcanmann** [bashtage/linearmodels#219]
Hello!

Apologies for my general ignorance and inexperience in programming. 

I was trying to use the Fama Macbeth estimator for a project. I can't seem to access all_params (before averaging). I'm sure it's easy enough for someone who programs well, but frankly I don't.

I looked at the source code for fama macbeth, and it would seem simple enough to pull from the calculation of params and include it in panelresults. 

That's all. Thank you!

**Comment by bashtage** [comment]
This is not easy since the [results instance](https://bashtage.github.io/linearmodels/panel/results.html#linearmodels.panel.results.PanelResults) is shared across panel models and so only tracks the estimate and its standard error

**Comment by lycanthropes** [comment]
Hi, @bashtage , is there any examples about FamaMecbath regression. I do not know whether your code of FamaMecbath regression includes time series regression or not. According to the documentation , it doesn't include time series regression but I want to make it clear because in the textbooks FamaMecbeth regression sometimes includes time series regression so as to get the estimated beta .

**Comment by bashtage** [comment]
I don't think there are any examples, but here is the explanation of what is going on:

https://bashtage.github.io/linearmodels/panel/panel/linearmodels.panel.model.FamaMacBeth.html
