### ISSUE TITLE
IV results object being modified without doing so?

### ISSUE THREAD

**Issue by elnoch5** [bashtage/linearmodels#414]
I estimated a model with the following code:
```
formula = 'y ~ 1 + X1 + X2 + X3 + W1_X1 + W1_X2 + W1_X3 + [Wy ~ W2_X1 + W2_X2]' # + W3_X1 + W3_X2 + W3_X3]'
mod = IV2SLS.from_formula(formula, data1).fit(cov_type="unadjusted")
```
I then create a a list with all the exogenous variables using the following code:
```
Z1_cols = mod.first_stage.exog.cols
Z1_cols.extend(mod.first_stage.instr.cols)
Z1_cols
```
If I run that on a first pass, everything works ok, but if I try to run the last three lines of code again without reestimating the model, I get the following error:
 **Shape of passed values is (6125, 8), indices imply (6125, 10)**
And after that first run, even if I try to get the mod.first_stage instance, I get the same error. Any idea why this is happening if my code is not modifying the mod object?

**Comment by bashtage** [comment]
This is just python biting you.

When you run 
```
Z1_cols = mod.first_stage.exog.cols
Z1_cols.extend(mod.first_stage.instr.cols)
Z1_cols
```

You are mutating the list in place.  This be because `Z1_cols` is ` mod.first_stage.exog.cols`.  you can even run

```
Z1_cols is mod.first_stage.exog.cols
```

which will return true.  You need to copy the list before you modify it.


This will create a shallow copy. 

```
Z1_cols = mod.first_stage.exog.cols[:]
Z1_cols.extend(mod.first_stage.instr.cols)
Z1_cols
```

You can create a deep copy (if you need it, but I don't think you will) using

```

```
from copy import deepcopy
Z1_cols = deepcopy(mod.first_stage.exog.cols)
Z1_cols.extend(mod.first_stage.instr.cols)
Z1_cols
```

I'm going to close this as answered.  If you still have trouble, please continue to post here.
