### ISSUE TITLE
API consistency with statsmodels

### ISSUE THREAD

**Issue by spillz** [bashtage/linearmodels#96]
I noticed a few inconsistencies with how statsmodels works. For example, the results summary is a method in SM but a property in LM. Is this intentional?

I also see that predict method is missing, but it is implemented for many SM models. Are there plans to implement a predict function? Handling fixed effects (and lagged dependent variables if implemented) would be nice.

**Comment by jbrockmendel** [comment]
I'll also ask about the relationship to statsmodels.  Both this and "arch" look really well put-together.  How do you decide what goes in these packages vs what you contribute to sm?

**Comment by bashtage** [comment]
> For example, the results summary is a method in SM but a property in LM. Is this intentional?

Yes, this is intentional.  It has no arguments and so I find it simplest to use properties for values that do not accept options.

> I also see that predict method is missing, but it is implemented for many SM models. Are there plans to implement a predict function? Handling fixed effects (and lagged dependent variables if implemented) would be nice.

predict is conceptually hard in FE models since one has to think hard about what a FE is.  In the standard fixed-T, large-N framework, fixed effects cannot be consistently estimated and so I can't see how a "prediction" is meaningful. Predict is similarly difficult for many other estimators, e.g., Between Effects or First Difference.   It is also very fragile when models can be specified using a formula since the prediction matrix has to be carefully constructed to match the original data structure.

**Comment by bashtage** [comment]
> I'll also ask about the relationship to statsmodels. Both this and "arch" look really well put-together. How do you decide what goes in these packages vs what you contribute to sm?

They try to be SM-like although there are differences, as noted above. I tried to make some large changes through SM to the unit root stuff but I found the process too slow to get in and the release schedule too long for my tastes- when I write something that is well tested, I prefer to make it easily available for users to install.  There are other challenges specified to linearmodels such as the time it takes to run the test suite which would timeout travis for statsmdoels.
